apiVersion: v1
kind: Service
metadata:
  name: traefik-svc
  namespace: traefik
  annotations:
    lb.kubesphere.io/v1alpha1: openelb
    protocol.openelb.kubesphere.io/v1alpha1: layer2
    eip.openelb.kubesphere.io/v1alpha2: eip-pool
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      name: web
      port: 80

    - protocol: TCP
      name: admin
      port: 8080

    - protocol: TCP
      name: websecure
      port: 443

    - protocol: TCP
      name: tcpep
      port: 8083

    - protocol: UDP
      name: udpep
      port: 8084

  selector:
    app: traefik